language: go
go:
 - tip

install:
  - go get -t ./...

script:
 - go build
 - go get golang.org/x/tools/cmd/vet
 - go vet
 - go test -v ./...                       # Run unit tests (verbose output)
 #- cp testsetup/test.conf.json conf.json  # Put our test config in place
 #- ./calendarpi &                         # Run ourself in the background
