language: go
go:
 - tip

install:
  - go get -t ./...
  - npm install cuke-monkey -g

script:
 - go build
 - go test -v ./...                       # Run unit tests (verbose output)
 - cp testsetup/test.conf.json conf.json  # Put our test config in place
 - ./calendarpi &                         # Run ourself in the background
 - cuke-monkey                            # Run our selenium tests
